package:
  name: ggmap
  version: 0.9.0

source:
  git_url: https://github.com/sjanssen2/ggmap.git

build:
  number: 1

test:
  commands:
    make test

requirements:
  build:
    scikit-bio >=0.5
    pandas
    biom-format >=2.1.6
    basemap
    matplotlib
    seaborn ==0.7.1
    numpy
    pillow
    networkx
    basemap
    basemap-data-hires

  run:
    scikit-bio >=0.5
    pandas
    biom-format >=2.1.6
    basemap
    matplotlib
    seaborn ==0.7.1
    numpy
    pillow
    networkx
    basemap
    basemap-data-hires

about:
  home: https://github.com/sjanssen2/ggmap
  summary: Collection of functions to analyse microbiome data.
